#
#Sat Oct 03 18:07:28 COT 2026
goog\:chromeOptions={args\=[--no-sandbox, --disable-dev-shm-usage, --window-size\=1440,1000, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
